export enum Tag {
    DnaDiscovered = 'dnaDiscovered',
    AntibodyReportDiscovered = 'antibody-report-discovered',
    FoodSensitivityReportDiscovered = 'foot-sensitivity-report-discovered',
    HeartHealthUkReportDiscovered = 'heart-health-uk-report-discovered',
    HeartHealthReportDiscovered = 'heart-health-report-discovered',
    TermsAgreed = 'terms-agreed',
    PrivacyAgreed = 'privacy-policy-agreed',
    InformedAgreed = 'informed-consent',
    OptOutOfResearch = 'opt-out-of-research',
    CarrierViewed = 'carrier-viewed',
    CancerViewed = 'cancer-viewed',
    AncestryViewed = 'ancestry-viewed',
    UpgradePremiumStarted = 'upgrade-premium-started',
    UpgradePremiumReady = 'upgrade-premium-ready',
    UpgradeVitalStarted = 'upgrade-vital-started',
    UpgradeVitalReady = 'upgrade-vital-ready',
    ActivationConsentAgreed = 'activation-consent',
    ReportViewed = 'report-viewed',
    CountryAdded = 'country-added',
    NotificationEnabled = 'notification-enabled',
    UpgradeWalkthroughViewed = 'upgrade-walkthrough-viewed',
    NewReportLaunched2022 = 'new-report-launched-2022',
}
